### ISSUE TITLE
java.lang.IllegalArgumentExceptionPacket too big (is 20257875, should be less than 8388608): net.minecraft.class_2788@7cf24ecb

### ISSUE THREAD

**Issue by TheButterbrotMan** [SigmundGranaas/forgero#134]
It seems like forgero is causing this problem, when im trying to join my multiplayer server, singpleplayer works

https://bytebin.lucko.me/9cABmfkww5

**Comment by TheButterbrotMan** [comment]
I see you coded this mod: https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler 

You are aware of this problem allready?

**Comment by TheButterbrotMan** [comment]
Seems to be connected to #118

**Comment by TheButterbrotMan** [comment]
It seems like your mod doesnt fix my problem.

**Comment by SigmundGranaas** [comment]
My mod only doubles the packet size, but the reported packet size is 2.4 times the size. I'll update the mod to increase the packet size header limit by 10x, and we can check if that solves the problem. New mod file is uploaded on  [CurseForge](https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler/files/3809876)

**Comment by SigmundGranaas** [comment]
Forgero seems to increase the packet size by quite a bit, have you tested if removing Forgero is the only mod removal that fixes this problem? During my testing with another mod pack, I found that I could remove other mods as well, which removed the issue with the packet size. Of course removing mods is not really a solution, but I was wondering if the issue lies with the amount of mods, or if there is a root issue with Forgero. If so I would like to fix it. However, it might also be possible that this issue simply comes from Forgero being the last "Big Packet Mod" to be added to the pack, which spills the packets size over the limit. I dunno.

It would be nice if you could share more of your findings once you have tried the updated packet size increaser!

**Comment by TheButterbrotMan** [comment]
> Forgero seems to increase the packet size by quite a bit, have you tested if removing Forgero is the only mod removal that fixes this problem? During my testing with another mod pack, I found that I could remove other mods as well, which removed the issue with the packet size. Of course removing mods is not really a solution, but I was wondering if the issue lies with the amount of mods, or if there is a root issue with Forgero. If so I would like to fix it. However, it might also be possible that this issue simply comes from Forgero being the last "Big Packet Mod" to be added to the pack, which spills the packets size over the limit. I dunno.
> 
> It would be nice if you could share more of your findings once you have tried the updated packet size increaser!

I can confirm this. Its not directly connected to your mod, but possible your mod is one of the bigger ones cuz the lot of stuff it is adding. When i remove other big mods like Botania, Create it also works again.

**Comment by TheButterbrotMan** [comment]
Thank you for the update of your mod. Ill add this along Forgero with the next update into my modpack.

**Comment by SigmundGranaas** [comment]
That is nice to hear, that'll probably save me a couple of hours of wasted debugging! I'll probably look into how I can reduce the packet footprint of Forgero. Did the new mod solve your problem?

**Comment by TheButterbrotMan** [comment]
Havent tested yet. But i think so. Will reopen this if i should encounter any problems again.
