### ISSUE TITLE
How can i get Forgero Beta release to work on earlier saves?

### ISSUE THREAD

**Issue by TheButterbrotMan** [SigmundGranaas/forgero#168]
"Forgero Beta release - THIS RELEASE WILL CRASH IF USED ON SAVES WITH EARLIER FORGERO VERSIONS"

**Comment by SigmundGranaas** [comment]
Forgero 0.9.0 changes how items and resources are named. This is a breaking change from earlier versions. This means that all items have different identifier between 0.9.0 and all earlier versions. This is done due to severe limitations with the old system, and makes it a lot easier to create custom resources for newer versions.
Unfortunately this means that it is not possible to make earlier saves work 100% with this update. Forgero items from old saves will disappear, and some combination of tools from old saves might cause crashes. For the most part it works fine, but I put the warning there to make it clear that this update contains breaking changes.
