### ISSUE TITLE
Advanced Netherite compatibility

### ISSUE THREAD

**Issue by DanMeadWasTaken** [SigmundGranaas/forgero#449]
[Advanced netherite](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite-fabric) materials being able to be used in the mod.

**Comment by SigmundGranaas** [comment]
That looks interesting! Basic support for new materials are easy to add through extensions, but it looks like a big part of this mod is the accented netherite with other materials. Forgero deals very poorly with generating anything but a clean palette, so that might be a challenge.

This would make for an interesting addition to the palette system, by extending it to support material accents as well. It would be an interesting way to add more depth to existing materials as well, so it could be interesting to look into.

**Comment by Nol-inuse** [comment]
y e s

**Comment by JorisDeBeer** [comment]
Done
