### ISSUE TITLE
latest release forgero-fabric-0.10.8+1.19.2 Startup crash on large modpack - likely mod interaction issue low priority

### ISSUE THREAD

**Issue by ArmouredDrood** [SigmundGranaas/forgero#544]
Startup crash on latest release.

initially presented as ftb chunks in first crashlog: https://pastebin.com/DRsxXNhi
removed ftb chunks, crashlog here: https://pastebin.com/ArX37Pa8

Caused by: java.lang.NullPointerException: Cannot invoke "c**om.sigmundgranaas.forgero.core.registry.StateCollection.all()" because "com.sigmundgranaas.forgero.core.ForgeroStateRegistry.STATES" is null**
	at com.sigmundgranaas.forgero.fabric.toolstats.ToolStatTagGenerator.generateTags(ToolStatTagGenerator.java:16)
	at com.sigmundgranaas.forgero.fabric.ForgeroCompatInitializer.onInitialize(ForgeroCompatInitializer.java:26)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)

This is in a large modpack, likely not an issue on your side.
Figured I would bring it to your attention before 12yo's in your curseforge comments.

Low priority. Thank you for your work. Cool mod :)

**Comment by ArmouredDrood** [comment]
realized I forgot to mention that I downgraded 1 release and did not experience the crash.

**Comment by SigmundGranaas** [comment]
Hey, thanks for the issue!
It seems like the compat module was loaded early for some reason, and tried accessing the core registry before Forgero had finished setting up things correctly. Fixing this issue should be fairly easy, but I am going to look into exactly how this happened, before slapping a lazy check on it to ensure it does not happen again.

**Comment by SigmundGranaas** [comment]
I believe this issue largely stems from the lack of a proper service layer to handle internal registry interactions, so I created another issue to track the implementation and rework of the current registry implementation, into a service layer. This can be tracked here. #545 

For the moment I will patch this really quickly so that this issue will be fixed before I get around to implementing the proper solution to this problem.
