### ISSUE TITLE
Only some repair kits can be used to repair tools

### ISSUE THREAD

**Issue by CandyGumdrop** [SigmundGranaas/forgero#605]
I'm finding that while all repair kits are craftable, only diamond, gold, copper, and netherite are usable for repairing tools.  Looking in EMI, these are the only ones which have tool repairing recipes available.  Notably, the iron repair kit does not work, and also I've noticed the tooltip name for just this one repair kit shows as `item.forgero.iron_repair_kit` instead of `Iron Repair Kit` like the others.

**Comment by SigmundGranaas** [comment]
Iron was used as the first test for using tags instead of direct id mappings in the iron property files, so there might still be issues with the tag mapping not being resolved properly in the repair kit recipes. Does this extend to the wood types, or is iron the only kit that does not work? If it's only iron that does not work, then we can be sure that it's the tag resolution that is the issue.

**Comment by CandyGumdrop** [comment]
None of the stone or wooden repair kits work either.
