### ISSUE TITLE
Things to do in balancing branch for 0.11

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#697]
- [x] Polar bear palette broke -> dont know how to fix? 
- [x] Add dragon scale (as was promised for 0.11 gems)
- [x] Add dye slots to refined and extended tools
- [x] Add mining level composite that actually works
- [x] Complete check if all lang files are there (upgrades are a bit hard too spot) 
- [x] Check on balancing itself (probably just push it and wait for feedback)

**Comment by SigmundGranaas** [comment]
General review comments:

- [x] - Upgrade and composite rarity values seems to be the same for some materials. Causing the rarity to increase by a huge amount when upgraded. (Diamond, polar bear pelt.)
- [ ] - Default bindings have -1 attack speed
- [x] - Pickaxe head tip reinforcement missing good description. This also applies to most extended heads.
- [ ] - Now that we have upgrade station, I can remove the type descriptor from slots
- [ ] - Rarity values for mastercrafted/refined gear seems to have increases by a huge amount. This cause issues with the loot system
- [x] - Oak, birch diorite and andesite have the same rarity levels? This seems to come from this:
 {
         "id": "schematic-rarity-composite",
         "type": "RARITY",
         "order": "BASE",
         "context": "COMPOSITE",
         "operation": "MULTIPLICATION",
         "value": 0.2
       }
- [x]       in most schematics. I would think having a 1x rarity multiplier would make sense here. Increase the worst stone variants to be 15 in rarity maybe?
- [x] - Axes have significant differing attack speed values from vanilla, but I assume this is due to Weight being the only attribute affecting attack speed.
- [x] - Also, axes and swords have the same baseline weight, so they have the same attack speed.
- [x] - Guard material slots should probably also be named reinforcement
- [x] - The echo shard palette's contrast is a little too sharp
- [x] - Prismarine's darkest palette values should be darker

  That's all I have for now. In general, the values seem to line up really well with vanilla stuff, it seems like the mastercrafted and other extended variants still require some tweaking, but I can try to also put in some effort to get that done as well.

 Also, well done! This is amazing work :clap:

**Comment by JorisDeBeer** [comment]
- [x] Stone doesnt get converted to cobblestone in upgradestation anymore
- [x] Adding material doesnt decrease rarity in my eyes. Weight does as its way less material than a toolhead. That was my thought process behind keeping rarity attributes the same. What you want here. 
- [ ] We need to create a rarity baseline. I need to know when the system changes the colour around with rarity etc to create realistic rarities to be real.
- [ ] Metalbindings add more durability in expense of some miningspeed while softbindings add some speed in return for less durability -> thats why the lose miningspeed. Also matter op opinion. what you want sigg
- [ ] BambooHandle is bugged for some reason.
- [x] Pommels are still bugged
- [x] New type descriptions dont work in upgrade station tools with handle
- [ ] 


What are the type descriptors? Smithing etc right?

**Comment by JorisDeBeer** [comment]
I added 0.5 less attackspeed to all axehead schematics so it ranges from 0.7 to 1.25.

This fixes both swords and axes having the same attackspeed and puts axes more in range with vanilla
