### ISSUE TITLE
CTD/Mod conflict with Great Big World/Terrablender

### ISSUE THREAD

**Issue by RorrinNadd** [SigmundGranaas/forgero#708]
I narrowed my crashes down to a combination of this mod and GBW/TB. Removed GBW + TB to keep this mod. This mod would work with wood items, but when trying to pull copper parts or iron, etc from the crafting bench it would immediately CTD. I'm new to this so I'm not sure what part of those other mods conflicts here so I just removed them unfortunately. I'm attaching the associated crash report. 
[crash-2023-08-25_22.51.48-client.txt](https://github.com/SigmundGranaas/forgero/files/12444466/crash-2023-08-25_22.51.48-client.txt)

**Comment by SigmundGranaas** [comment]
Hello! Thanks for posting the issue.
It seems like the system is crashing because an item in your crafting grid has a registered recipe remainder, but when trying to get this remainder as an item, a null (Empty) is returned, which causes a crash. There's no direct link to any Forgero code here in this crashlog, only Fabric's item api, so to understand how Forgero might have caused this issue, I would need to see exactly what is causing the issue, preferably an image or something similar.

**Comment by SigmundGranaas** [comment]
Closing this as stale.
