### ISSUE TITLE
Extended branch revisit

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#710]
### Current extended branch
We feel that the extended branch a the moment doesnt do itself justice. Tools fall short to the tiered stuff (mastercrafted/refined), arent unique enough, textures are a outdated compared to the rest and stats dont fit the tools. 

**CURRENT PLANS**

- Create different series so tools fit a theme, have a unique spot in the roster and can be added to their own pack for organizing sake. 
- Rebalance all tools

**IDEAS FOR SERIES**

-  Fortified  (Artisan) -> Slower, More durability (LATER DATE?)
-  Defensive (armored (this just sounds really cool and fits fight me) -> More armor, ?? (PLANNED FOR ARMORS AND SHIELDS)
-  Offensive (Imperial) -> More attack damage/tools that normally cant be used offensive can now, less durability 
-  Utility (Creative? Creativity? Revolutionary?)-> Hammers etc? Depends on how unique I can make this
-  Lightweight (lightweight)-> Less hunger, less weight THROWABLE SMALLER VARIANTS OF NORMAL WEAPONS -> KNIFES, THROWING HATCHETS!!!
- Exotic/oriental package with tools from different worlds/era's (nikana's, etc) 

**Exotic** 

- Katana
- [x] Katana blade
- [x] Katana guard
- [x] Katana Reinforcement
- [x] Katana Handle
- Rapier
- [x] Rapier blade
- [x] Rapier guard
- [x] Rapier Reinforcement
- Kunai
- [x] Kunai blade
- [x] Kunai handle
- [x] Kunai Reinforcement
- [x] Kunai grip 

**Imperial** 

- Broadsword
- [x] sword blade
- [ ] sword Reinforcement
- Battle Axe
- [x] Axe blade
- [x] Axe Reinforcement
- Scythe
- [ ] Scythe blade
- [ ] Scythe handle
- [ ] Scythe Reinforcement
- Spear
- [x] Spear head
- [x] Spear Reinforcement
- Mace
- [x] Mace head
- [x] Mace Reinforcement
- Club
- [x] Club head
- [x] Club Reinforcement
- War Hammer
- [x] Hammer head
- [x] Hammer Reinforcement
- Mechanized Sawblade -> Needs animation support
- [x] Sawblade
- [x] Sawblade Reinforcement
- [x] Guard

**Lightweight (need a name tbh)** 

- Tomahawk
- [ ] Axe blade
- [ ] Axe Reinforcement
- [ ] Axe handle
- Throwing Knife
- [x] Knife blade
- [x] Knife handle
- [x] Knife Reinforcement

**Revolutionarity/utility** 

- Chisel
- [x] Chisel blade
- [x] Chisel handle
- Sickle (not sure, models for this one are very scuffed
- [x] Sickle blade
- [x] Sickle Reinforcement
- Pick Mattock
- [x] Mattock / Pickaxe head
- [x] Mattock / Pickaxe Reinforcement
- Cutter Mattock
- [x] Mattock / axe head
- [x] Mattock / axe Reinforcement

**Broad Mining**
- Hammer (3 x 3 Mining)
- [x] Hammer head
- [x] Hammer Reinforcement
- Spade Vein? 
- [x] Spade head
- [x] Spade Reinforcement
- Entrenching Tool (Pick/offensive/shovel??)
- [x] Entrenching head 3x3
- [x] Entrenching Reinforcement
- Mandrill Pickaxe Vein ore
- [x] Mandrill head 
- [x] Mandrill Reinforcement
- Felling Axe -> Vein wood
- [x] Felling Axe head 
- [x] Fellin Axe Reinforcement

**FUTURE PLANS (MORE CODE NEEDED)**

- [ ] Unique animated textures
- [ ] Unique animated stats/abilities
- [ ] 32 x 32 even maybe? I dont really like this myself so if someone wants to?
- [ ] Predicates used in some way?

**Comment by SigmundGranaas** [comment]
Man's already aiming for 0.12, that's bold :rocket: 

I really like the idea of extending the extended pack in Forgero, and I think that it really does need a revamp to stay relevant. I remember you and Klato talking about new variants of weapons with concrete themes, like Imperial or something along those lines. I like the idea of each theme having a strong point, so it's easy to know what each series does, just like the refined and mastercrafted. One think I would consider is naming the theme something similar to the aesthetic of the tool, instead of just something similar to the attribute it gives, as the conditions already apply a very similar name to parts when they're applied.

**Comment by SigmundGranaas** [comment]
We should also make a list of all of the different new features/attributes you think would be nice to have to create so that all new weapons/tools can have unique abilities/effects.

I know poison, bleeding and biome specific attributes are wanted, but if we have a longer list of attributes/features, it makes it easier for me to plan how to implement stuff in the long run.

**Comment by SigmundGranaas** [comment]
Eyy! I really like the new names as well. The potential exotic pack sounds like a ton of fun to create as well. It could be fun to experiment with standalone parts there as well, as there might be some types of weapons/tools that might be hard to manage through a simple schematic and the current data system.

**Comment by SigmundGranaas** [comment]
Also, the throwing stuff sounds really fun! Ideally I want all tools to be throwable, but most of them should be really shit. Here the actual throwable variants could have a lot more accuracy/range.

**Comment by JorisDeBeer** [comment]
I am closing this as all model files for 1.0 are in and only some technical stuff we are aware of is left
