### ISSUE TITLE
EMI Loot v0.6.1 incompatibility (fixed with update) 

### ISSUE THREAD

**Issue by Fevix** [SigmundGranaas/forgero#743]
https://mclo.gs/XRyJqqB

I'm seeing a lot of errors like `[14:06:27] [Render thread/ERROR]:
 Parsing error loading recipe forgero:ebony-broadsword_blade
com.google.gson.JsonSyntaxException: Unknown item 'byg:ebony'` all through the logs, but the game gets to the main menu just fine. When trying to load into a world, however, it fails with `[14:06:42] [Netty Local Client IO #0/ERROR]:
 Exception occurred in netty pipeline
java.lang.StringIndexOutOfBoundsException: offset 586, count 12827, length 5433`

Removing Forgero fixes this.

**Comment by JorisDeBeer** [comment]
First and foremost there are ALOT of errors in that log. Also alot not caused by forgero. The parsing errors and the type errors shouldnt make it crash. It just says it doesnt recognize the ID's we put in the files for some reason. Weird as some of them also reference normal minecraft ID's that should work. 

The exit errors is related to emi_loot I have personally not used that so I wouldnt know if that works together. 

The inbetween errors are more interesting as those literally show the recipe creator breaking for some reason. 

I cant narrow this down, maybe sigmund could but its not a conflict with BYG. Its a mod conflict with something else probably.

**Comment by Steveplays28** [comment]
On `1.20.1` BYG works for me, though I did compile BYG from source myself. I also haven't had any issues with `1.19.2`, though I've tested that a lot less.
There should be EMI Loot compat as well, Sigmund added that ~half a year ago.

**Comment by SigmundGranaas** [comment]
This looks a lot like the issue that was caused by emi loot + forgero. In that case it was due to the number of loot entries on some entities

**Comment by SigmundGranaas** [comment]
This looks a lot like the issue that was caused by emi loot + forgero. In that case it was due to the number of loot entries on some entities

**Comment by SigmundGranaas** [comment]
fzzyhmstrs.emi_loot.util.TextKey.fromBuf(TextKey.java:278) ~[emi_loot-0.6.1+1.19.jar:?]


Yes, I think this is the same issue again.

**Comment by SigmundGranaas** [comment]
I would recommend upgrading the emi loot version and trying again. 0.6.1 was released in February.

**Comment by Fevix** [comment]
Will do that when I get home tonight. I just left for work. Thanks for the quick response!

**Comment by SigmundGranaas** [comment]
Np, hope it works!

**Comment by Fevix** [comment]
Updating EMI-Loot worked! I'm in and can see all the forgero recipes in EMI.
