### ISSUE TITLE
Forgero crash with Identity mod due to "SoulEntity"

### ISSUE THREAD

**Issue by Borailuce99** [SigmundGranaas/forgero#801]
Hi, I installed some mods to play with friends and found this really interesting mod similar to Tinker's Construct which we all love. In addittion, we installed 'Identity' mod to make some games and have fun but whenever we open the 'Identity' GUI, the game crash and the crash-reports shows that it is because an error like:
_Cannot invoke "net.minecraft.class_5132.method_26862(net.minecraft.class_1320)" because "this.field_23711" is null
at com.sigmundgranaas.forgero.minecraft.common.entity.SoulEntity.<init>(SoulEntity.java:66)_

Searching on the repo I read that Soul Entity is still WIP and is not implemented on any version (only for experimental) so, is there any way to disable this entity to avoid crashing the game with the 'Identity' incompatibility? Is there any new version being developed taking this error in account to solve it? When will it be the next update?

Thanks a lot in advance.

**Comment by SigmundGranaas** [comment]
Thanks for bringing up the issue!

I am working on modularizing the entire mod, so it's easier to manage different parts of the mods, and disable stuff that is still wip. It seems like this issue is coming from the lack of an initialized AttributeContainer in the entity. I'll try to patch this quickly, but obviously the long term solution is to separate the entire soul stuff into a module which can be included only if we want to.

**Comment by Borailuce99** [comment]
Sorry to reopen this issue, but i forgot to mention the problem is on minecraft 1.20.1 with fabric 0.91.0+1.20.1 verions.
