### ISSUE TITLE
Question: Change durability for vanilla tools

### ISSUE THREAD

**Issue by Gamerbolts** [SigmundGranaas/forgero#823]
Hello again, no bug report this time but a suggestion. Let me know if I am incorrect but I do not see an option for this.

There are some items in my modpack that require the vanilla tools to craft. I removed vanilla recipes so that people were forced to use Forgero. Would it be possible to have a config option to change all vanilla tools to 1 durability essentially making them worthless but still craftable for those recipes. I know this is something I believe Tinker's Construct did so I am not sure if it something you have considered or plan on implementing. Would be a great help!

**Comment by SigmundGranaas** [comment]
An option like this would make a lot of sense for people looking to create a Forgero only experience in a modpack. Setting the vanilla tools to 1 durability requires a bit of an hack which might be incompatible with other mods, so keeping an option like this in the main repository is probably not the best idea. I think the best approach would be to create a separate mod that disables vanilla tools so it's easier to manage. I got a bit too much stuff to work on, so I probably can't make this myself, but I hope someone does, because it would be a nice feature :+1:

**Comment by Gamerbolts** [comment]
Yeah if I could mod I would do it lol. I think what I will do is enable the recipe. As that seems to be the only way to allow some of those crafting recipes from other mods. Also each tester for my modpack the first thing they say to me is "I can't make tools" LOL

**Comment by Steveplays28** [comment]
There's an option for removing vanilla tools' crafting recipes and another option for removing vanilla tools from the loot pool. This works well enough usually, but there's still some compat issues on the backlog, such as with Nox. In general you should also use a datapack to clean up modded loot tables and recipes. You can also use tags such as `c:hidden_from_recipe_viewers` to hide the crafting recipes from recipe viewers such as EMI.

**Comment by Gamerbolts** [comment]
ok thank you
