### ISSUE TITLE
Error when joining LAN world.

### ISSUE THREAD

**Issue by tagrimo** [SigmundGranaas/forgero#851]
Using Forgero 0.11.8 

Fabric 0.15.6

Minecraft 1.19.2

Here is the log file

[latest.log](https://github.com/SigmundGranaas/forgero/files/14416473/latest.log)

![Screenshot 2024-02-27 022356](https://github.com/SigmundGranaas/forgero/assets/139603512/fc78e6ac-6e45-41f5-b5fe-f6b1fec2dbe9)

Any help would be appreciated thank you so much.

**Comment by SigmundGranaas** [comment]
Thanks for the issue! 
This seems different than issues reported earlier that was caused by emi-loot and very long loot entries. It has only been reported on 1.19.2, so I dunno if it's specific to that version or not.

Does this happen when only using forgero and fabric-api when joining local worlds? If so It's and internal issue. If not it's a mod compat issue, and I'll very likely need help figuring out which mods are have issues.

**Comment by tagrimo** [comment]
Error happened again with only fabric api and forgero.

![image](https://github.com/SigmundGranaas/forgero/assets/139603512/1905277a-d68c-4b94-bcc2-83a670512f28)

[latest.log](https://github.com/SigmundGranaas/forgero/files/14417083/latest.log)

**Comment by SigmundGranaas** [comment]
That's good news, I'll be able to debug it properly, then. I will try to check it out when I have time :+1:

**Comment by JorisDeBeer** [comment]
Closed as we offer no support for 1.19.2 and this is stale
